export const PROVINCIAS = [
  "Buenos Aires",
  "Ciudad Autónoma de Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

export const LOCALIDADES_POR_PROVINCIA: Record<string, string[]> = {
  "Buenos Aires": [
    "Adrogué", "Aguas Corrientes", "Alberti", "Alejandro Korn", "Arrecifes",
    "Arroyo Dulce", "Avellaneda", "Ayacucho", "Azul", "Bahía Blanca",
    "Balcarce", "Banfield", "Baradero", "Batán", "Bella Vista",
    "Berazategui", "Berisso", "Bernal", "Bolívar", "Bragado",
    "Brandsen", "Burzaco", "Cañuelas", "Campana", "Capitán Sarmiento",
    "Carhué", "Carlos Casares", "Carlos Tejedor", "Carmen de Areco", "Castelli",
    "Chacabuco", "Chascomús", "Chivilcoy", "City Bell", "Claypole",
    "Coronel Dorrego", "Coronel Pringles", "Coronel Rosales", "Coronel Suárez", "Daireaux",
    "Del Viso", "Dolores", "Don Torcuato", "El Jagüel", "El Palomar",
    "El Pato", "El Talar", "Ensenada", "Escobar", "Esquina",
    "Esteban Echeverría", "Ezpeleta", "Ezeiza", "Florencio Varela", "Florentino Ameghino",
    "Garín", "General Alvarado", "General Alvear", "General Belgrano", "General Guido",
    "General La Madrid", "General Las Heras", "General Lavalle", "General Madariaga", "General Paz",
    "General Pueyrredón", "General Rodríguez", "General San Martín", "General Viamonte", "General Villegas",
    "Glew", "González Catán", "Grand Bourg", "Guaminí", "Haedo",
    "Hipólito Yrigoyen", "Hurlingham", "Ingeniero Maschwitz", "Ituzaingó", "José C. Paz",
    "José León Suárez", "José Mármol", "Junín", "La Costa", "La Matanza",
    "La Plata", "La Reja", "Lanús", "Laprida", "Las Flores",
    "Leandro N. Alem", "Lincoln", "Lobería", "Lobos", "Lomas de Zamora",
    "Longchamps", "Los Cardales", "Los Hornos", "Los Polvorines", "Luján",
    "Magdalena", "Maipú", "Malvinas Argentinas", "Manuel Belgrano", "Mar Chiquita",
    "Mar de Ajó", "Mar del Plata", "Mar del Tuyú", "Marcos Paz", "Matheu",
    "Melchor Romero", "Mercedes", "Merlo", "Miramar", "Monte",
    "Monte Grande", "Monte Hermoso", "Moreno", "Morón", "Munro",
    "Navarro", "Necochea", "Olavarría", "Olivos", "Patagones",
    "Pehuajó", "Pellegrini", "Pergamino", "Pila", "Pilar",
    "Pinamar", "Presidente Perón", "Punta Indio", "Quilmes", "Ramallo",
    "Ranelagh", "Rauch", "Rivadavia", "Rojas", "Roque Pérez",
    "Saavedra", "Saladillo", "Salliqueló", "Salto", "San Andrés de Giles",
    "San Antonio de Areco", "San Bernardo", "San Cayetano", "San Clemente del Tuyú", "San Fernando",
    "San Francisco Solano", "San Isidro", "San Miguel", "San Nicolás de los Arroyos", "San Pedro",
    "San Vicente", "Santos Lugares", "Suipacha", "Tandil", "Tapiales",
    "Tapalqué", "Temperley", "Tigre", "Tordillo", "Tornquist",
    "Trenque Lauquen", "Tres Arroyos", "Tres de Febrero", "Tres Lomas", "Tristán Suárez",
    "Turdera", "Vicente López", "Villa Ballester", "Villa Gesell", "Villa Madero",
    "Villa Martelli", "Villa Tranquila", "Villarino", "William Morris", "Zárate",
  ],
  "Ciudad Autónoma de Buenos Aires": [
    "Agronomía", "Almagro", "Balvanera", "Barracas", "Belgrano",
    "Boedo", "Caballito", "Chacarita", "Coghlan", "Colegiales",
    "Constitución", "Flores", "Floresta", "La Boca", "La Paternal",
    "Liniers", "Mataderos", "Monte Castro", "Monserrat", "Nueva Pompeya",
    "Núñez", "Palermo", "Parque Avellaneda", "Parque Chacabuco",
    "Parque Chas", "Parque Patricios", "Puerto Madero", "Recoleta",
    "Retiro", "Saavedra", "San Cristóbal", "San Nicolás", "San Telmo",
    "Vélez Sársfield", "Versalles", "Villa Crespo", "Villa del Parque",
    "Villa Devoto", "Villa General Mitre", "Villa Lugano", "Villa Luro",
    "Villa Ortúzar", "Villa Pueyrredón", "Villa Real", "Villa Riachuelo",
    "Villa Santa Rita", "Villa Soldati", "Villa Urquiza",
  ],
  "Catamarca": [
    "Andalgalá", "Antofagasta de la Sierra", "Aconquija", "Belén", "Capayán",
    "Catamarca Capital", "El Alto", "El Rodeo", "Fiambalá", "Fray Mamerto Esquiú",
    "Hualfín", "La Paz", "La Puerta", "Londres", "Los Altos",
    "Paclín", "Pomán", "Recreo", "San Fernando del Valle de Catamarca", "San José",
    "San Martin", "Santa María", "Santa Rosa", "Saujil", "Tinogasta",
    "Valle Viejo", "Villa Vil",
  ],
  "Chaco": [
    "Añatuya", "Barranqueras", "Basail", "Charata", "Chorotis",
    "Corzuela", "El Sauzalito", "Fontana", "Gancedo", "General José de San Martín",
    "General Pinedo", "General Vedia", "Hermoso Campo", "Isla del Cerrito", "Juan José Castelli",
    "La Clotilde", "La Eduvigis", "La Escondida", "La Verde", "Las Breñas",
    "Las Garcitas", "Machagai", "Makallé", "Miraflores", "Napenay",
    "Pampa Almirón", "Pampa del Infierno", "Pampa del Indio", "Presidencia de la Plaza", "Presidencia Roca",
    "Presidencia Saenz Peña", "Puerto Bermejo", "Puerto Eva Perón", "Puerto Tirol", "Puerto Vilelas",
    "Quitilipi", "Resistencia", "Roque Sáenz Peña", "Samuhú", "San Bernardo",
    "Santa Sylvina", "Taco Pozo", "Tres Isletas", "Villa Ángela", "Wichi",
  ],
  "Chubut": [
    "Alto Río Senguer", "Camarones", "Cholila", "Comodoro Rivadavia", "Cushamen",
    "Dolavon", "El Bolsón (parte)", "El Maitén", "El Hoyo", "Esquel",
    "Gaiman", "Gastre", "Gobernador Costa", "Lago Puelo", "Las Plumas",
    "Paso de Indios", "Puerto Madryn", "Puerto Pirámides", "Rawson", "Río Mayo",
    "Río Pico", "Sarmiento", "Tecka", "Trelew", "Trevelín",
  ],
  "Córdoba": [
    "Adelia María", "Alta Gracia", "Almafuerte", "Arroyito", "Balnearia",
    "Bell Ville", "Brinkmann", "Cabrera", "Camilo Aldao", "Canals",
    "Capilla del Monte", "Carrilobo", "Colonia Caroya", "Colonia Tirolesa", "Córdoba Capital",
    "Cosquín", "Cruz Alta", "Cruz del Eje", "Dean Funes", "El Tío",
    "Embalse", "General Cabrera", "General Deheza", "Hernando", "Huinca Renancó",
    "Jesús María", "La Carlota", "La Falda", "La Para", "La Playosa",
    "Laboulaye", "Las Varillas", "Leones", "Los Cocos", "Luque",
    "Marcos Juárez", "Malagueño", "Mendiolaza", "Monte Cristo", "Monte Maíz",
    "Morrison", "Morteros", "Mina Clavero", "Oliva", "Oncativo",
    "Pilar", "Quilino", "Río Ceballos", "Río Cuarto", "Río Primero",
    "Río Segundo", "Río Tercero", "Sacanta", "Salsipuedes", "San Francisco",
    "San Marcos Sierra", "Saturnino María Laspiur", "Tancacha", "Unquillo", "Valle Hermoso",
    "Villa Allende", "Villa Carlos Paz", "Villa Cura Brochero", "Villa Dolores", "Villa General Belgrano",
    "Villa Giardino", "Villa María", "Villa Nueva", "Villa Rumipal", "Wenceslao Escalante",
  ],
  "Corrientes": [
    "Bella Vista", "Berón de Astrada", "Bonpland", "Capital (Corrientes)", "Chavarría",
    "Colonia Liebig", "Concepción", "Curuzú Cuatiá", "Empedrado", "Esquina",
    "Felipe Yofré", "Garruchos", "General Alvear", "General Paz", "Gobernador Valentín Virasoro",
    "Goya", "Itatí", "Ituzaingó", "La Cruz", "Lavalle",
    "Loreto", "Mburucuyá", "Mercedes", "Mocoretá", "Monte Caseros",
    "Palmar Grande", "Paso de los Libres", "Perugorría", "Saladas", "San Carlos",
    "San Cosme", "San Luis del Palmar", "San Martín", "San Miguel", "San Roque",
    "Santa Ana", "Santa Rosa", "Santo Tomé", "Sauce", "Yapeyú",
  ],
  "Entre Ríos": [
    "Basavilbaso", "Ceibas", "Chajarí", "Colón", "Concepción del Uruguay",
    "Concordia", "Crespo", "Diamante", "El Pingo", "Federación",
    "Federal", "Feliciano", "Gualeguay", "Gualeguaychú", "Herrera",
    "La Paz", "Las Cuevas", "Larroque", "Lucas González", "Maciá",
    "Nogoyá", "Paraná", "Rosario del Tala", "San José", "San Salvador",
    "Seguí", "Tala", "Ubajay", "Urdinarrain", "Victoria",
    "Villa Constitución", "Villa Elisa", "Villa Paranacito", "Villaguay", "Viale",
  ],
  "Formosa": [
    "Clorinda", "El Colorado", "Estanislao del Campo", "Formosa Capital", "General Enrique Mosconi",
    "General Lucio Victorio Mansilla", "General Manuel Belgrano", "Gran Guardia", "Ibarreta", "Ingeniero Juárez",
    "Laguna Blanca", "Las Lomitas", "Mayor Luis Jorge Fontana", "Pirané", "Pozo del Tigre",
    "Riacho He Hé", "San Martín II", "Villa General Manuel Belgrano", "Villa Dos Trece",
  ],
  "Jujuy": [
    "Abra Pampa", "Caimancito", "Calilegua", "El Carmen", "El Fuerte",
    "Fraile Pintado", "Humahuaca", "La Esperanza", "La Mendieta", "La Quiaca",
    "Ledesma", "Libertador General San Martín", "Maimará", "Monterrico", "Palpalá",
    "Perico", "Pichanal", "Puesto Viejo", "Purmamarca", "Rinconada",
    "San Antonio", "San Pedro de Jujuy", "San Salvador de Jujuy", "Santa Bárbara", "Santa Catalina",
    "Susques", "Tilcara", "Tumbaya", "Yala", "Yavi",
  ],
  "La Pampa": [
    "Alpachiri", "Alta Italia", "Anguil", "Arata", "Bernardo Larroude",
    "Bernasconi", "Catriló", "Colonia Barón", "Eduardo Castex", "General Acha",
    "General Campos", "General Manuel Campos", "General Pico", "Guatraché", "Ingeniero Luiggi",
    "Intendente Alvear", "La Adela", "La Maruja", "Lonquimay", "Luan Toro",
    "Macachín", "Metileo", "Miramar", "Parera", "Quemú Quemú",
    "Rancul", "Realicó", "Relmo", "Santa Isabel", "Santa Rosa",
    "Toay", "Trenel", "Unanué", "Victorica", "Winifreda",
  ],
  "La Rioja": [
    "Aimogasta", "Aminga", "Arauco", "Chamical", "Chepes",
    "Chilecito", "Chuquis", "General Ángel Vicente Peñaloza", "Guandacol", "Independencia",
    "La Rioja Capital", "Los Robles", "Malanzán", "Nonogasta", "Patquía",
    "San Blas de los Sauces", "Sanagasta", "Ulapes", "Villa Castelli", "Villa Nidia",
    "Villa San José de Vinchina", "Villa Unión", "Vinchina",
  ],
  "Mendoza": [
    "Ciudad de Mendoza", "Dorrego", "El Algarrobal", "El Bermejo", "General Alvear",
    "Godoy Cruz", "Guaymallén", "Junín", "La Consulta", "La Paz",
    "Las Heras", "Lavalle", "Luján de Cuyo", "Maipú", "Malargüe",
    "Palmira", "Pedregal", "Perdriel", "Real del Padre",
    "Rivadavia", "Rodeo del Medio", "Russell", "San Carlos", "San Martín",
    "San Rafael", "Santa Rosa", "Tunuyán", "Tupungato", "Uspallata",
    "Villa Nueva",
  ],
  "Misiones": [
    "Alba Posse", "Almafuerte", "Apóstoles", "Aristóbulo del Valle", "Arroyo del Medio",
    "Bernardo de Irigoyen", "Bonpland", "Caá Yarí", "Candelaria", "Capioví",
    "Caraguatay", "Cerro Azul", "Cerro Corá", "Colonia Aurora", "Colonia Polana",
    "Concepción de la Sierra", "Corpus", "Dos Arroyos", "El Dorado", "El Soberbio",
    "Eldorado", "Fachinal", "Florentino Ameghino", "Garuhapé", "Garupá",
    "General Alvear", "Guaraní", "Iguazú", "Jardín América", "Leandro N. Alem",
    "Loreto", "Mártires", "Mojón Grande", "Montecarlo", "Oberá",
    "Posadas", "Puerto Esperanza", "Puerto Iguazú", "Puerto Leoni", "Puerto Piray",
    "Puerto Rico", "Ruiz de Montoya", "San Ignacio", "San Javier", "San Pedro",
    "San Vicente", "Santa Ana", "Santa María", "Santo Pipó", "Tres Capones",
    "Veinticinco de Mayo", "Wanda",
  ],
  "Neuquén": [
    "Aluminé", "Añelo", "Buta Ranquil", "Caviahue", "Centenario",
    "Chos Malal", "Cutral Có", "El Cholar", "El Huecú", "Huinganco",
    "Junín de los Andes", "Las Coloradas", "Las Lajas", "Las Ovejas", "Loncopué",
    "Los Catutos", "Los Miches", "Neuquén Capital", "Picún Leufú", "Piedra del Águila",
    "Plaza Huincul", "Plottier", "Rincón de los Sauces", "San Martín de los Andes", "San Patricio del Chañar",
    "Senillosa", "Tricao Malal", "Villa El Chocón", "Villa La Angostura", "Villa Pehuenia",
    "Zapala",
  ],
  "Río Negro": [
    "Bariloche", "Catriel", "Cervantes", "Choele Choel", "Cinco Saltos",
    "Cipolletti", "Comallo", "Contralmirante Cordero", "El Bolsón", "El Cóndor",
    "El Juncal", "Fiske Menuco", "General Enrique Godoy", "General Fernández Oro", "General Roca",
    "Guardia Mitre", "Ingeniero Huergo", "Ingeniero Jacobacci", "Lamarque", "Las Grutas",
    "Luis Beltrán", "Maquinchao", "Mencué", "Ministro Ramos Mexía", "Ñorquinco",
    "Palmetto", "Pilcaniyeu", "San Antonio Oeste", "San Carlos de Bariloche", "Sierra Colorada",
    "Sierra Grande", "Sierra Pailemán", "Valcheta", "Viedma", "Villa Mascardi",
    "Villa Regina",
  ],
  "Salta": [
    "Aguaray", "Cafayate", "Campo Quijano", "Capital (Salta)", "Cerrillos",
    "Chicoana", "Embarcación", "El Bordo", "El Galpón", "El Quebrachal",
    "General Güemes", "General Mosconi", "Hipólito Yrigoyen", "Iruya", "J.V. González",
    "La Caldera", "La Candelaria", "La Merced", "La Poma", "La Viña",
    "Metán", "Molinos", "Orán", "Pichanal", "Rivadavia",
    "Rosario de la Frontera", "Rosario de Lerma", "Salvador Mazza", "San Antonio de los Cobres", "San Carlos",
    "San Ramón de la Nueva Orán", "Santa Victoria Este", "Santa Victoria Oeste", "Tartagal", "Tolloche",
  ],
  "San Juan": [
    "Albardón", "Angaco", "Calingasta", "Caucete",
    "Chimbas", "Cienaga", "Iglesia", "Jachal", "Media Agua",
    "Médano de Oro", "Nueve de Julio", "Pocito", "Rawson", "Rivadavia",
    "San Agustín del Valle Fértil", "San José de Jáchal", "San Juan Capital", "San Martín", "Santa Lucía",
    "Sarmiento", "Ullum", "Valle Fértil", "Veinticinco de Mayo", "Villa Aberastain",
    "Villa Barboza", "Villa Krause", "Zonda",
  ],
  "San Luis": [
    "Arizona", "Beazley", "Buena Esperanza", "Candelaria", "Carpintería",
    "Chosmes", "Concarán", "Desaguadero", "El Trapiche", "Fraga",
    "Juan Llerena", "La Punta", "La Toma", "Lafinur", "Leandro N. Alem",
    "Luján", "Mercedes", "Merlo", "Naschel", "Navia",
    "Nogolí", "Papagayos", "Pozo Hondo", "Quines", "Rincón del Carmen",
    "San Francisco del Monte de Oro", "San Luis Capital", "San Martín", "Santa Rosa del Conlara", "Tilisarao",
    "Unión", "Villa de La Quebrada", "Villa de Merlo", "Villa del Carmen", "Villa Dolores (parte)",
    "Villa General Roca", "Villa Mercedes",
  ],
  "Santa Cruz": [
    "28 de Noviembre", "Caleta Olivia", "Cañadón Seco", "Comandante Luis Piedra Buena", "El Calafate",
    "El Chaltén", "El Turbio", "Gobernador Gregores", "Julia Dufour", "Las Heras",
    "Los Antiguos", "Perito Moreno", "Puerto Deseado", "Puerto Madryn (parte)", "Puerto Natales (parte)",
    "Puerto San Julián", "Río Gallegos", "Río Turbio", "Tres Lagos", "Veintiocho de Noviembre",
  ],
  "Santa Fe": [
    "Armstrong", "Arroyo Seco", "Avellaneda", "Cañada de Gómez", "Capitán Bermúdez",
    "Carcarañá", "Casilda", "Ceres", "Coronda", "Empalme Villa Constitución",
    "Esperanza", "Firmat", "Funes", "Gálvez", "Granadero Baigorria",
    "Laguna Paiva", "Las Parejas", "Las Rosas", "Máximo Paz", "Melincué",
    "Pérez", "Puerto General San Martín", "Rafaela", "Reconquista", "Recreo",
    "Roldan", "Rosario", "Rufino", "San Cristóbal", "San Genaro",
    "San Javier", "San Jorge", "San Justo", "San Lorenzo", "Santa Fe Capital",
    "Santo Tomé", "Sastre", "Tostado", "Venado Tuerto", "Vera",
    "Villa Cañás", "Villa Constitución", "Villa Gobernador Gálvez", "Villa Ocampo", "Wheelwright",
  ],
  "Santiago del Estero": [
    "Añatuya", "Averías", "Beltrán", "Campo Gallo", "Capital (Santiago del Estero)",
    "Clodomira", "Colonia El Simbolar", "Colonia Dora", "Colonia Tinco", "El Hoyo",
    "Fernández", "Frías", "Garza", "Gramilla", "Herrera",
    "Icaño", "La Banda", "Lavalle", "Loreto", "Los Telares",
    "Maco", "Malbrán", "Manogasta", "Monte Quemado", "Pampa Muyoj",
    "Pinto", "Quimilí", "Río Hondo", "Sachayoj", "San Pedro",
    "Selva", "Suncho Corral", "Taboada", "Termas de Río Hondo", "Tintina",
    "Vilelas", "Villa Atamisqui", "Villa La Punta", "Villa Ojo de Agua", "Villa Salavina",
    "Villa Unión",
  ],
  "Tierra del Fuego": [
    "Río Grande", "Tolhuin", "Ushuaia",
  ],
  "Tucumán": [
    "Acheral", "Aguilares", "Alderetes", "Amaicha del Valle", "Amberes",
    "Atahona", "Banda del Río Salí", "Bella Vista", "Burruyacú", "Capitán Cáceres",
    "Chicligasta", "Concepción", "El Bracho", "El Cadillal", "El Manantial",
    "Famaillá", "Graneros", "Juan Bautista Alberdi", "La Cocha", "Las Cejas",
    "Las Talitas", "Lastenia", "Lules", "Manuela Pedraza", "Monteros",
    "Nogalito", "Ranchillos", "Río Chico", "Rumi Punco", "San Miguel de Tucumán",
    "Santa Cruz", "Santa Rosa de Leales", "Simoca", "Tafí del Valle", "Tafí Viejo",
    "Trancas", "Vipos", "Yerba Buena",
  ],
};
